#! /bin/sh

####Evironment Path
export PATH="$PATH:$HOME/.config/bspwm/scripts"

if [[ $(xrandr -q | grep 'DP-1 connected') ]]; then
	xrandr --output eDP-1 --mode 1366x768 --rotate normal --output DP-1 --primary --mode 1920x1080 --rotate normal --right-of eDP-1
fi

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config pointer_action resize_corner
bspc config pointer_modifier super
bspc config pointer_action1 move


bspc monitor eDP-1 -d 1  
bspc monitor DP-1 -d 2 3 4 5 6


bspc config border_width         2
bspc config window_gap          1

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on             
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Tilix desktop='^1' follow=on
bspc rule -a Code desktop='^2' follow=on
bspc rule -a Brave-browser desktop='^3' follow=on
bspc rule -a Thunar desktop='^4' follow=on

#AutoStart#
feh --bg-fill /home/rugery/Imágenes/wallpaper.png &
$HOME/.config/polybar/launch.sh --cuts 
picom &
dunst &
power.sh &
