#!/bin/bash

# Función para mostrar una notificación con el brillo actual
function send_notification() {
    brightness=$(cat /sys/class/backlight/intel_backlight/brightness)
    max_brightness=$(cat /sys/class/backlight/intel_backlight/max_brightness)
    brightness_percent=$(bc -l <<< "scale=2; $brightness*100/$max_brightness")
    brightness_rounded=$(printf "%.0f" "$brightness_percent")
    bar_length=$((brightness_rounded / 10))
    dunstify -a "changebrightness" -u low -r 9991 -h int:value:"$brightness_rounded" -h string:x-canonical-private-synchronous:brightness "Brillo: $brightness_rounded%" "$bar"
}



# Si no se especifica ningún argumento, mostrar una notificación con el brillo actual
if [ -z "$1" ]; then
    send_notification
    exit 0
fi

# Obtener el valor actual de brillo
brightness=$(brightnessctl -m | awk -F "," '{print $1}')

# Ajustar el brillo según el argumento proporcionado
case "$1" in
    up)
        brightnessctl set +10%
        send_notification
        ;;
    down)
        brightnessctl set 10%-
        send_notification
        ;;
    *)
        echo "Uso: $0 {up|down}"
        exit 1
        ;;
esac

exit 0
